version: '3.8'

services:
  fedora-osh-db:
    image: docker.io/postgres:12
    container_name: fedora-osh-db
    hostname: fedora-osh-db
    environment:
      POSTGRES_PASSWORD: velryba
      POSTGRES_USER: openscanhub
      POSTGRES_DB: openscanhub
    ports:
      - "5432:5432"
    networks:
      - internal-network

  fedora-osh-hub:
    image: fedora-osh-hub
    build:
      context: .
      dockerfile: hub.Dockerfile
    container_name: fedora-osh-hub
    hostname: fedora-osh-hub
    depends_on:
      - fedora-osh-db
    ports:
      - "8080:8080"
    networks:
      - internal-network
    volumes:
      - ./:/src:ro,z
    stdin_open: true
    tty: true

  fedora-osh-worker:
    image: fedora-osh-worker
    build:
      context: .
      dockerfile: worker.Dockerfile
    container_name: fedora-osh-worker
    hostname: fedora-osh-worker
    depends_on:
      - osh-hub
    networks:
      - internal-network
    volumes:
      - ./:/src:ro,z
    privileged: true
    stdin_open: true
    tty: true

  fedora-osh-client:
    image: fedora-osh-client
    build:
      context: .
      dockerfile: client.Dockerfile
    container_name: fedora-osh-client
    hostname: fedora-osh-client
    depends_on:
      - osh-hub
    networks:
      - internal-network
    volumes:
      - ./:/src:ro,z
    stdin_open: true
    tty: true

networks:
  internal-network:
