apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/route-disabled: "false"
    app.openshift.io/vcs-ref: ""
    app.openshift.io/vcs-uri: https://github.com/siteshwar/openscanhub-deployment-configs.git
    deployment.kubernetes.io/revision: "3"
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"osh-hub:latest","namespace":"covscan"},"fieldPath":"spec.template.spec.containers[?(@.name==\"osh-hub\")].image","pause":"false"}]'
    openshift.io/generated-by: OpenShiftWebConsole
  creationTimestamp: "2023-07-12T08:55:39Z"
  generation: 3
  labels:
    app: osh-hub
    app.kubernetes.io/component: osh-hub
    app.kubernetes.io/instance: osh-hub
    app.kubernetes.io/name: osh-hub
    app.kubernetes.io/part-of: openscanhub
  name: osh-hub
  namespace: communishift-openscanhub
  resourceVersion: "3565519657"
  uid: be90c51e-1ebf-411e-86e2-e9a8e4c6ac05
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: osh-hub
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: osh-hub
        deployment: osh-hub
    spec:
      containers:
      - image: quay.io/svashisht/openscanhub:latest
        imagePullPolicy: Always
        name: osh-hub
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
